#!/bin/sh
# Legt prisma/migrations/20260830120000_init aus schema.prisma an.
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT/packages/db"
test -f prisma/schema.prisma || { echo "packages/db/prisma/schema.prisma fehlt"; exit 1; }

export DATABASE_URL="${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/seo_toolbox?schema=public}"
export DIRECT_DATABASE_URL="${DIRECT_DATABASE_URL:-$DATABASE_URL}"
export SHADOW_DATABASE_URL="${SHADOW_DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/seo_toolbox_shadow?schema=public}"

DIR="prisma/migrations/20260830120000_init"
mkdir -p "$DIR"
pnpm exec prisma migrate diff \
  --from-empty \
  --to-schema-datamodel prisma/schema.prisma \
  --script > "$DIR/migration.sql"

cat > prisma/migrations/migration_lock.toml << 'EOF'
# Please do not edit this file.
provider = "postgresql"
EOF

echo "geschrieben: $DIR/migration.sql ($(wc -l < "$DIR/migration.sql") Zeilen)"
echo
echo "DB schon per db push da:"
echo "  pnpm exec prisma migrate resolve --applied 20260830120000_init"
echo "Leere DB:"
echo "  pnpm exec prisma migrate deploy"
