#!/bin/sh
# Einmalig: erste Migration aus dem aktuellen schema.prisma.
# Danach: Schema-Änderungen nur noch mit `pnpm db:migrate`.
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT/packages/db"
NAME="${1:-init}"
STAMP="$(date +%Y%m%d%H%M%S)"
DIR="prisma/migrations/${STAMP}_${NAME}"
mkdir -p "$DIR"
pnpm exec prisma migrate diff \
  --from-empty \
  --to-schema-datamodel prisma/schema.prisma \
  --script > "$DIR/migration.sql"
cat > prisma/migrations/migration_lock.toml << 'EOF'
# Please do not edit this file.
provider = "postgresql"
EOF
echo "geschrieben: $DIR/migration.sql"
echo
echo "Neue, leere DB:     pnpm db:migrate:deploy"
echo "DB existiert schon (früher db push):"
echo "  pnpm --filter db exec prisma migrate resolve --applied ${STAMP}_${NAME}"
echo "Dann committen: packages/db/prisma/migrations/"
